POST http://127.0.0.1:8000/api/users/3/remove-role
Authorization: Bearer 9|Sf0aIIzA0eqXZ16deGakDpJD9My893vlgtnLRb0N3938dc77
Content-Type: application/json
Accept: application/json


{
  "role_id": 3
}
